frontend:
  deploymentContainer:
    image: draadnl/openstad-frontend:755673327
auth:
  deploymentContainer:
    image: openstad/auth:v0.10.0
admin:
  deploymentContainer:
    image: openstad/admin:v0.10.2
api:
  deploymentContainer:
    image: draadnl/openstad-api:754608218
image:
  deploymentContainer:
    image: openstad/image:v0.7.0
